"""empty message

Revision ID: d7712c187395
Revises: 
Create Date: 2019-02-27 10:41:53.454216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7712c187395'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_loan_log_due_date'), 'loan_log', ['due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_log_due_date'), table_name='loan_log')
    # ### end Alembic commands ###
